name: Update Empty JSON-LD URLs v1.1
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-jsonld-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Find and update empty URLs in JSON-LD schema
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Repository name: $REPO_NAME"
        
        find . -type f -name "*.html" | while read -r htmlFile; do
          echo "Processing file: $htmlFile"
          
          # Create a temporary file
          temp_file=$(mktemp)
          
          # Process the file line by line
          while IFS= read -r line; do
            if [[ $line == *'<script type="application/ld+json"'* ]]; then
              # Print the script tag line as is
              echo "$line" >> "$temp_file"
              
              # Read the JSON content
              read -r json_content
              
              # Process the JSON content to update empty URLs
              processed_json=$(echo "$json_content" | jq --arg url "https://$REPO_NAME" '
                def update_empty_urls:
                  if type == "object" then
                    if .url? == "" then
                      .url = $url
                    else
                      . |= with_entries(.value |= update_empty_urls)
                    end
                  elif type == "array" then
                    map(update_empty_urls)
                  else
                    .
                  end;
                update_empty_urls
              ')
              
              # Write the processed JSON
              echo "$processed_json" >> "$temp_file"
              
              # Read and write the closing script tag
              read -r closing_line
              echo "$closing_line" >> "$temp_file"
            else
              # Write non-JSON-LD lines as they are
              echo "$line" >> "$temp_file"
            fi
          done < "$htmlFile"
          
          # Replace original file with processed content
          mv "$temp_file" "$htmlFile"
        done
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update empty URLs in JSON-LD schema" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
