name: Update Empty JSON-LD URLs v1.3
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-jsonld-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Find and update empty URLs in JSON-LD schema
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Repository name: $REPO_NAME"
        
        find . -type f -name "*.html" | while read -r htmlFile; do
          echo "Processing file: $htmlFile"
          
          # Create a temporary file
          temp_file=$(mktemp)
          
          # Use perl to process the file and only modify JSON-LD content
          perl -0777 -pe '
            s/(<script type="application\/ld\+json" class="rank-math-schema">)(.*?)(<\/script>)/
              my $start = $1;
              my $json = $2;
              my $end = $3;
              # Replace empty URLs with the site URL
              $json =~ s/"url":""/"url":"https:\/\/'"$REPO_NAME"'"/g;
              $json =~ s/"item":\{"@id":"",/"item":{"@id":"https:\/\/'"$REPO_NAME"'",/g;
              $start . $json . $end
            /gse' "$htmlFile" > "$temp_file"
          
          # Check if the temporary file is not empty before moving
          if [ -s "$temp_file" ]; then
            mv "$temp_file" "$htmlFile"
          else
            echo "Warning: Empty output file generated for $htmlFile, skipping..."
            rm "$temp_file"
          fi
        done
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update empty URLs in JSON-LD schema" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
