name: Update Empty JSON-LD URLs v1.2
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-jsonld-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Find and update empty URLs in JSON-LD schema
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Repository name: $REPO_NAME"
        
        find . -type f -name "*.html" | while read -r htmlFile; do
          echo "Processing file: $htmlFile"
          
          # Create a temporary file
          temp_file=$(mktemp)
          
          # Flag to track if we're inside JSON-LD script tag
          in_script=false
          json_content=""
          
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ $line == *'<script type="application/ld+json'* ]]; then
              in_script=true
              echo "$line" >> "$temp_file"
              continue
            fi
            
            if [[ $in_script == true ]]; then
              if [[ $line == *'</script>'* ]]; then
                # Process collected JSON content
                if [ ! -z "$json_content" ]; then
                  processed_json=$(echo "$json_content" | jq --arg url "https://$REPO_NAME" '
                    def update_empty_urls:
                      if type == "object" then
                        to_entries | map(
                          if .value == "" and .key == "url" then
                            {key: .key, value: $url}
                          else if .value | type == "object" then
                            {key: .key, value: (.value | update_empty_urls)}
                          else if .value | type == "array" then
                            {key: .key, value: (.value | map(update_empty_urls))}
                          else
                            .
                          end
                        ) | from_entries
                      elif type == "array" then
                        map(update_empty_urls)
                      else
                        .
                      end;
                    update_empty_urls
                  ' 2>/dev/null || echo "$json_content")
                  echo "$processed_json" >> "$temp_file"
                fi
                echo "$line" >> "$temp_file"
                in_script=false
                json_content=""
              else
                json_content+="$line"
              fi
            else
              echo "$line" >> "$temp_file"
            fi
          done < "$htmlFile"
          
          # Replace original file with processed content
          mv "$temp_file" "$htmlFile"
        done
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update empty URLs in JSON-LD schema" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
